### ISSUE TITLE
Excursion Funnel missing effects

### ISSUE THREAD

**Issue by WolfeStrider** [xoxor4d/p2-rtx#90]
Bug reported by wolfe_strider on Trello on November 5th

Description:
~~1. The emitters that create the funnel are missing trails~~
2. The main effect should be the same speed that the player or physics props are supposed to be traveling in the funnel defined in a keyvalue for the entity
3. There is a subtle copy of the primary effect that you can see traveling in the opposite direction sometimes
~~4. There is supposed to be an overlay/decal effect where the funnel ends when it hits a wall and when it goes through a portal~~
5. Missing tiny blue round particles that fly up from the emitter and fly the entire length on the funnel

Examples:

Compare the Excursion Funnels in these two videos:
https://www.youtube.com/watch?v=XH64iKdvczw
https://www.youtube.com/watch?v=vAtLK9qIRsY
<img width="523" alt="Untitled" src="https://github.com/user-attachments/assets/200bf69f-5e62-43fc-af6c-d78f83dcb036">

Preview image:
![Image](https://github.com/user-attachments/assets/28e40afc-c127-4008-9a52-959e53ba6854)

**Comment by xoxor4d** [comment]
This was fixed with commit: [particles: fix performance on spritecards (get rid of VB modifications)](https://github.com/xoxor4d/p2-rtx/commit/10c9d9f33747fe8544723833251a295881de1758)

**Comment by WolfeStrider** [comment]
> This was fixed with commit: [particles: fix performance on spritecards (get rid of VB modifications)](https://github.com/xoxor4d/p2-rtx/commit/10c9d9f33747fe8544723833251a295881de1758)

@xoxor4d I checked this before I opened this issue and although it has improved a lot it still isn't completely fixed. Check the items on the list in the description of the issue that aren't crossed out

**Comment by WolfeStrider** [comment]
If you wish I can re-grab updated screenshots of the incomplete effects and update this issue

**Comment by WolfeStrider** [comment]
I updated the description of the issue with an example issue of number 5 on the list

**Comment by xoxor4d** [comment]
Sorry meant to post this on #91 😂
